### ISSUE TITLE
Illegal Memory Access in DDP Multi-GPU Training

### ISSUE THREAD

**Issue by yzchen08** [SNU-ARC/flashTP#1]
When I train using a single GPU, everything works perfectly. Training and inference speed increases by 5x. Memory consumption is reduced by half. However, when I enable DistributedDataParallel (DDP) for 2-GPU training, the first training step runs successfully, but the second step fails with the following error, and only rank1 raises the error:
```
[rank1]:     node_hiddens = node_hiddens.div(self.avg_num_neighbors ** 0.5)
[rank1]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: RuntimeError: CUDA error: an illegal memory access was encountered
```
Additionally, when I use e3nn for multi-GPU training, everything works fine without any issues.
Here is the code snippet where the error occurs:
```python
from torch import distributed as dist
self.tp = flashTP_e3nn.uvu_TP(
            self.irreps_hidden,
            self.irreps_sh,
            irreps_mid,
            instructions, 
            device=f"cuda:{dist.get_rank()}", 
            )
...
node_hiddens = self.tp(node_hiddens, data['edge_sh'], weight, edge_dst.to(torch.int32), edge_src.to(torch.int32))
node_hiddens = node_hiddens.div(self.avg_num_neighbors ** 0.5)
...
```
Environment:
```
python: 3.11.13
Driver Version: 575.57.08
CUDA Version: 12.4
torch: 2.6.0+cu124
Distributed backend: nccl
```

**Comment by sylee0124** [comment]
Hi thanks for opening this issue.

Could you share a bit more context around the error you’re seeing?
Are all other inputs (e.g. node_hiddens, data['edge_sh'], weight, edge_dst, edge_src) on the same cuda device?

**Comment by yzchen08** [comment]
> Hi thanks for opening this issue.
> 
> Could you share a bit more context around the error you’re seeing? Are all other inputs (e.g. node_hiddens, data['edge_sh'], weight, edge_dst, edge_src) on the same cuda device?

I used 2 A40-48G GPU, and following code to print device:
```python
node_hiddens = self.tp(node_hiddens, data['edge_sh'], weight, edge_dst.to(torch.int32), edge_src.to(torch.int32))
print(dist.get_rank(), node_hiddens.device, data['edge_sh'].device, weight.device, edge_dst.device, edge_src.device)
node_hiddens = node_hiddens.div(self.avg_num_neighbors ** 0.5)
```
and the error:
```
fused_uvu_TP_exp_opt_large
fused_uvu_TP_exp_opt_large
Need to tune SMEM_SIZE, using safe mode of SMEM_SIZE=48KB
SMEM_SIZE 47
using per_block_batch  [17, 7, 5]
Need to tune SMEM_SIZE, using safe mode of SMEM_SIZE=48KB
SMEM_SIZE 47
using per_block_batch  [17, 7, 5]
2025-07-22 16:50:14,929 - __main__ - INFO - total parameters: 20296904
2025-07-22 16:50:14,929 - __main__ - INFO - model train and validation results logged in ./log/run_100/metric_100.csv ...
2025-07-22 16:50:14,929 - __main__ - INFO - model checkpoints saved in ./log/run_100/ckpt_100/ and ./ckpt_bak/run_100/ckpt_100/...
2025-07-22 16:50:14,933 - __main__ - INFO - start step: 0, start epoch: 0, start batch idx: 0
Loading number of atoms or edge from file mpa_num_edges.pkl ...
Loading number of atoms or edge from file mpa_num_edges.pkl ...
2025-07-22 16:50:15,192 - __main__ - INFO - max_atoms_or_edges_per_batch=100000
Rank 0: assigned 6013754 samples
Rank 1: assigned 6013753 samples
Creating batches for rank 0: 100%|████████████████████████████████████████████████████████████| 6013754/6013754 [00:03<00:00, 1739605.49it/s]
Created 80748 batches
Will process 80748 batches
Creating batches for rank 1: 100%|████████████████████████████████████████████████████████████| 6013753/6013753 [00:03<00:00, 1730760.27it/s]
Created 80767 batches
Will process 80767 batches
0 cuda:0 cuda:0 cuda:0 cuda:0 cuda:0
0 cuda:0 cuda:0 cuda:0 cuda:0 cuda:0
0 cuda:0 cuda:0 cuda:0 cuda:0 cuda:0
0 cuda:0 cuda:0 cuda:0 cuda:0 cuda:0
0 cuda:0 cuda:0 cuda:0 cuda:0 cuda:0
0 cuda:0 cuda:0 cuda:0 cuda:0 cuda:0
0 cuda:0 cuda:0 cuda:0 cuda:0 cuda:0
0 cuda:0 cuda:0 cuda:0 cuda:0 cuda:0
1 cuda:1 cuda:1 cuda:1 cuda:1 cuda:1
1 cuda:1 cuda:1 cuda:1 cuda:1 cuda:1
1 cuda:1 cuda:1 cuda:1 cuda:1 cuda:1
1 cuda:1 cuda:1 cuda:1 cuda:1 cuda:1
1 cuda:1 cuda:1 cuda:1 cuda:1 cuda:1
1 cuda:1 cuda:1 cuda:1 cuda:1 cuda:1
1 cuda:1 cuda:1 cuda:1 cuda:1 cuda:1
1 cuda:1 cuda:1 cuda:1 cuda:1 cuda:1
2025-07-22 16:50:23,867 - __main__ - INFO - step: 1, learning rate: [0.0002001, 0.0002001]
2025-07-22 16:50:23,878 - __main__ - INFO - step: 1, loss weight: tensor([0.5000, 0.5000], device='cuda:0')
2025-07-22 16:50:23,879 - __main__ - INFO - step: 1, loss: 1.1852, energy: 0.6379, forces: 0.2685, stress: 0.2788, 
2025-07-22 16:50:23,879 - __main__ - INFO - train rmse energy: 3.5493, forces: 2.6390, stress: 0.1774, time: 2.0484
0 cuda:01  cuda:0 cuda:0 cuda:0cuda:1  cuda:0cuda:1
 cuda:1 cuda:1 cuda:1
0 cuda:0 cuda:0 cuda:0 cuda:0 cuda:0
0 cuda:0 cuda:0 cuda:0 cuda:0 cuda:0
0 cuda:0 cuda:0 cuda:0 cuda:0 cuda:0
0 cuda:0 cuda:0 cuda:0 cuda:0 cuda:0
0 cuda:0 cuda:0 cuda:0 cuda:0 cuda:0
0 cuda:0 cuda:0 cuda:0 cuda:0 cuda:0
0 cuda:0 cuda:0 cuda:0 cuda:0 cuda:0
CUDA Runtime Error at: /root/workdir/flashTP/flashTP_e3nn/sptp_exp_opt_large/fwd_sptp_linear_v2_shared_exp.cu:223
an illegal memory access was encountered cudaFuncSetAttribute( fwd_sptp_lienar_kernel_v2_shared_exp<float>, cudaFuncAttributeMaxDynamicSharedMemorySize, shared_memory_bytes)
```

**Comment by sylee0124** [comment]
To help pinpoint exactly where the illegal memory access is happening, could you try the following:

* Enable CUDA launch blocking
At the top of your training script (before any CUDA calls), add:
```python3
import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
```
This will force all CUDA kernels to run synchronously and report errors at the point they occur.

* Synchronize after each training step
Immediately after your training step (e.g. after loss.backward() or optimizer.step()), add:
```python3
torch.cuda.synchronize()
```
This guarantees that any out‑of‑bounds or memory violations are caught right away, instead of at the start of next the step.

Additionally, in
[flashTP_e3nn/sptp_exp_opt_large/fused_e3nn_exp_opt_large.py](https://github.com/SNU-ARC/flashTP/blob/main/flashTP_e3nn/sptp_exp_opt_large/fused_e3nn_exp_opt_large.py#L714) at line 714
the per-GPU shared‐memory configuration is currently exit only for A100/H100, and for other GPUs it used default 48KB. 
To fully leverage the A40’s 99 KB of shared memory (compute capability 8.6), you can extend that check.

**Comment by yzchen08** [comment]
I figured out what was wrong. I did not set `torch.cuda.set_device(local_rank)` explicitly. This caused all processes to default to using `cuda:0` instead of their designated GPUs. PyTorch's native operations have built-in fault tolerance for device mismatches and can handle automatic data migration, which is why the code worked fine without flashTP.

**Comment by sylee0124** [comment]
Thank you for sharing the solution! I’m glad to hear the issue is resolved. I’ll close this issue once I’ve tracked down any tensors that were initialized without an explicit CUDA device rank.
